[package]
name = "ferrissight-storage"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
ferrissight-core.workspace = true
serde.workspace = true
uuid.workspace = true
async-trait.workspace = true
thiserror.workspace = true
mp4 = "0.14"
bytes = "1"
