[workspace]
members = ["crates/*"]
exclude = ["vendor/retina"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/mdai001/FerrisSight"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "net", "signal", "io-util", "io-std", "time", "sync"] }
axum = "0.8"
thiserror = "2"
async-trait = "0.1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt"] }
clap = { version = "4", features = ["derive", "env"] }
uuid = { version = "1", features = ["v4", "serde"] }
tower = { version = "0.5", features = ["util"] }
ferrissight-core = { path = "crates/ferrissight-core" }
ferrissight-camera = { path = "crates/ferrissight-camera" }
ferrissight-server = { path = "crates/ferrissight-server" }

[package]
name = "ferrissight"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false
include = ["/Cargo.toml", "/Cargo.lock", "/LICENSE", "/README.md", "/src/**", "/docs/**", "/examples/config.example.toml", "/vendor/retina/**"]

[dependencies]
ferrissight-server.workspace = true
tokio.workspace = true
clap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[profile.release]
strip = true
debug = false

[patch.crates-io]
retina = { path = "vendor/retina" }
